Disabled threaded loading to prevent crashes/errors.
One user reported the game crashing with a 10+ GB godot.log file, containing
millions of lines of this:

ERROR: Disconnecting nonexistent signal 'changed', slot: 142430:_recreate_quadrants.
   at: Object::_disconnect (core\object.cpp:1548) - Condition "!s->slot_map.has(target)" is true.

This appears to stem from Godot #34752
(https://github.com/godotengine/godot/issues/34752) which causes crashes when
connecting to objects from multiple threads. We only employ threads in two
places: when initially caching resources, and when initializing tilemaps for
Sharks.

I've disabled threaded loading to prevent this issue.

Threaded loading makes the game about 40% faster to initialize (3.358s versus
5.121s) so if these issues are resolved in the future, it might be nice to
re-enable it.